window.NANA_FOREX_ENV = {
  SUPABASE_URL: "https://xjmakedoqdbfafhbhjsj.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbWFrZWRvcWRiZmFmaGJoanNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMjQxNjksImV4cCI6MjA5NjYwMDE2OX0.301vOBOwx_Srai3mKlLAzBDCztKWOL5LTN5-v1_xklc"
};
